src/Website/Controllers/DefaultController.cs
namespace App.Controllers
{
    using Microsoft.AspNet.Mvc;

    //[Authorize]
    public class DefaultController : Controller
    {
        public IActionResult Home() => RedirectPermanent("~/Pages-and-Menus");

        public IActionResult NotFound()
        {
            // Some browsers always look for /favicon.ico
            if (Request.Path.Value == "/favicon.ico")
                return RedirectPermanent("~/Images/favicon.ico");

            //return new HttpNotFoundResult();
            //throw new HttpResponseException(HttpStatusCode.NotFound);
            throw new System.Web.HttpException(404, $"wtf brah!? '{Request.Path.Value}' is 404");
        }

        public IActionResult Error() => View("~/Views/Shared/Error.cshtml");

        ////[Route("pages-and-menus/dynamic-items/all-options")]
        ////[Route("pages-and-menus/dynamic-items/no-options")]
        ////[Route("pages-and-menus/dynamic-items/option")]
        ////[HttpGet][AllowAnonymous][ValidateAntiForgeryToken]
        //public IActionResult EmptyPage() => View($"~/Views{Request.Path.Value}.cshtml");
    }
}

src/Website/Controllers/_Pages/PagesAndMenus/DynamicItems/AllOptionsController.cs
namespace App.Controllers.PagesAndMenusDynamicItems
{
    using Microsoft.AspNet.Mvc;

    [Area("PagesAndMenus/DynamicItems")]
    [Route("Pages-and-Menus/Dynamic-Items/All-Options")]
    public class AllOptionsController : App.BasePageController
    {
        //[Route("")]
        //public IActionResult Default()
        //{
        //          return View();
        //	//return View($"~/Views/_Pages/PagesAndMenus/DynamicItems/AllOptions.cshtml");
        //	//return View($"~/Views/_Pages{Request.Path.Value}.cshtml");
        //}
    }
}

src/Website/Controllers/_Pages/PagesAndMenus/DynamicItems/DynamicItemsController.cs
namespace App.Controllers.PagesAndMenus
{
    using Microsoft.AspNet.Mvc;

    [Area("PagesAndMenus")]
    [Route("Pages-and-Menus/Dynamic-Items")]
    public class DynamicItemsController : App.BasePageController
    {
        //[Route("")]
        //public IActionResult Default()
        //{
        //          return View();
        //	//return View($"~/Views/_Pages/PagesAndMenus/DynamicItems/Default.cshtml");
        //	//return View($"~/Views/_Pages{Request.Path.Value}.cshtml");
        //}
    }
}

src/Website/Controllers/_Pages/PagesAndMenus/DynamicItems/NoOptionsController.cs
namespace App.Controllers.PagesAndMenusDynamicItems
{
    using Microsoft.AspNet.Mvc;

    [Area("PagesAndMenus/DynamicItems")]
    [Route("Pages-and-Menus/Dynamic-Items/No-Options")]
    public class NoOptionsController : App.BasePageController
    {
        //[Route("")]
        //public IActionResult Default()
        //{
        //          return View();
        //	//return View($"~/Views/_Pages/PagesAndMenus/DynamicItems/NoOptions.cshtml");
        //	//return View($"~/Views/_Pages{Request.Path.Value}.cshtml");
        //}
    }
}

src/Website/Controllers/_Pages/PagesAndMenus/DynamicItems/OptionController.cs
namespace App.Controllers.PagesAndMenusDynamicItems
{
    using Microsoft.AspNet.Mvc;

    [Area("PagesAndMenus/DynamicItems")]
    [Route("Pages-and-Menus/Dynamic-Items/Option")]
    public class OptionController : App.BasePageController
    {
        //[Route("")]
        //public IActionResult Default()
        //{
        //          return View();
        //	//return View($"~/Views/_Pages/PagesAndMenus/DynamicItems/Option.cshtml");
        //	//return View($"~/Views/_Pages{Request.Path.Value}.cshtml");
        //}
    }
}

src/Website/Controllers/_Pages/PagesAndMenus/PagesAndMenusController.cs
namespace App.Controllers.PagesAndMenus
{
    using Microsoft.AspNet.Mvc;

    [Area("PagesAndMenus")]
    [Route("Pages-and-Menus")]
    public class PagesAndMenusController : App.BasePageController
    {
        //[Route("")]
        //public IActionResult Default()
        //{
        //          return View();
        //	//return View($"~/Views/_Pages/PagesAndMenus/Default.cshtml");
        //	//return View($"~/Views/_Pages{Request.Path.Value}.cshtml");
        //}
    }
}

src/Website/Controllers/_Pages/PagesAndMenus/SubItem1/SideItem1Controller.cs
namespace App.Controllers.PagesAndMenusSubItem1
{
    using Microsoft.AspNet.Mvc;

    [Area("PagesAndMenus/SubItem1")]
    [Route("Pages-and-Menus/SubItem1/SideItem1")]
    public class SideItem1Controller : App.BasePageController
    {
        //[Route("")]
        //public IActionResult Default()
        //{
        //          return View();
        //	//return View($"~/Views/_Pages/PagesAndMenus/SubItem1/SideItem1.cshtml");
        //	//return View($"~/Views/_Pages{Request.Path.Value}.cshtml");
        //}
    }
}

src/Website/Controllers/_Pages/PagesAndMenus/SubItem1/SideItem2Controller.cs
namespace App.Controllers.PagesAndMenusSubItem1
{
    using Microsoft.AspNet.Mvc;

    [Area("PagesAndMenus/SubItem1")]
    [Route("Pages-and-Menus/SubItem1/SideItem2")]
    public class SideItem2Controller : App.BasePageController
    {
        //[Route("")]
        //public IActionResult Default()
        //{
        //          return View();
        //	//return View($"~/Views/_Pages/PagesAndMenus/SubItem1/SideItem2.cshtml");
        //	//return View($"~/Views/_Pages{Request.Path.Value}.cshtml");
        //}
    }
}

src/Website/Controllers/_Pages/PagesAndMenus/SubItem1/SideItem3Controller.cs
namespace App.Controllers.PagesAndMenusSubItem1
{
    using Microsoft.AspNet.Mvc;

    [Area("PagesAndMenus/SubItem1")]
    [Route("Pages-and-Menus/SubItem1/SideItem3")]
    public class SideItem3Controller : App.BasePageController
    {
        //[Route("")]
        //public IActionResult Default()
        //{
        //          return View();
        //	//return View($"~/Views/_Pages/PagesAndMenus/SubItem1/SideItem3.cshtml");
        //	//return View($"~/Views/_Pages{Request.Path.Value}.cshtml");
        //}
    }
}

src/Website/Controllers/_Pages/PagesAndMenus/SubItem1/SubItem1Controller.cs
namespace App.Controllers.PagesAndMenus
{
    using Microsoft.AspNet.Mvc;
    using MSharp.Framework.AspNet.Mvc;

    [Area("PagesAndMenus")]
    [Route("Pages-and-Menus/SubItem1")]
    public class SubItem1Controller : App.BasePageController
    {
        //[Activate]
        public LinkHelperService Link { get; set; }

        public SubItem1Controller(LinkHelperService link)
        {
            Link = link;
        }

        [Route("")]
        public override IActionResult Default()
        {
            return RedirectPermanent(Link.To("Default", "SideItem1", "PagesAndMenus/SubItem1").BuildUrl());
            //return View();
            //return View($"~/Views/_Pages/PagesAndMenus/SubItem1/Default.cshtml");
            //return View($"~/Views/_Pages{Request.Path.Value}.cshtml");
        }
    }
}

src/Website/Controllers/_Pages/PagesAndMenus/SubItem2Controller.cs
namespace App.Controllers.PagesAndMenus
{
    using Microsoft.AspNet.Mvc;

    [Area("PagesAndMenus")]
    [Route("Pages-and-Menus/SubItem2")]
    public class SubItem2Controller : App.BasePageController
    {
        //public IActionResult Default()
        //{
        //    ViewBag.Title = "SubItem2";
        //    //ViewBag.SubMenu = "PagesAndMenusMenu";
        //    //ViewBag.SubMenuArgs = new { Lorem = "Ipsum", Dolor = 517 };

        //    return View();
        //    //return View("DefaultPage");
        //    //return View($"~/Views/_Pages/PagesAndMenus/SubItem2.cshtml");
        //    //return View($"~/Views/_Pages{Request.Path.Value}.cshtml");
        //}
    }
}

src/Website/Views/_Pages/PagesAndMenus/Default.cshtml
@{
    ViewBag.Title = "Pages & Menus";
}

<div class="jumbotron">
    <h1>@ViewBag.Title</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>@Context.Request.Path.Value</h2>
        <p>Form start</p>
        @using (Html.BeginForm(FormMethod.Post))
        {
            <input type="submit" value="Postback" />}
        <p>Form end</p>
        @*@Html.ActionLink("Pages & Menus > DynamicItems > NoOptions", "Default", "NoOptions", new { Area = "PagesAndMenus/DynamicItems" });*@
        @*@Html.ActionLink("Pages & Menus > SubItem1 > SideItem2", "Default", "SubItem1", new { Area = "PagesAndMenus" });*@
    </div>
</div>

@if (ViewBag.SubMenu != null)
{
    @section submenu{
        @await Component.InvokeAsync("Module", ViewBag.SubMenu, ViewBag.SubMenuArgs)
    }
}

@if (ViewBag.SideMenu != null)
{
    @section sidemenu{
        @await Component.InvokeAsync("Module", ViewBag.SideMenu, ViewBag.SideMenuArgs)
    }
}

src/Website/Views/_Pages/PagesAndMenus/SubItem2.cshtml
<div class="jumbotron">
    <h1>@ViewBag.Title</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>@Context.Request.Path.Value</h2>
        <p>Form start</p>
        @using (Html.BeginForm(FormMethod.Post))
        {
            <input type="submit" value="Postback" />}
        <p>Form end</p>
        @*@Html.ActionLink("Pages & Menus > DynamicItems > NoOptions", "Default", "NoOptions", new { Area = "PagesAndMenus/DynamicItems" });*@
        @*@Html.ActionLink("Pages & Menus > SubItem1 > SideItem2", "Default", "SubItem1", new { Area = "PagesAndMenus" });*@
    </div>
</div>

@if (ViewBag.SubMenu != null)
{
    @section submenu{
        @await Component.InvokeAsync("Module", ViewBag.SubMenu, ViewBag.SubMenuArgs)
    }
}

@if (ViewBag.SideMenu != null)
{
    @section sidemenu{
        @await Component.InvokeAsync("Module", ViewBag.SideMenu, ViewBag.SideMenuArgs)
    }
}